#####################################
#                                   #
#              Config               #
#                                   #
#####################################
# roles/wordpress/tasks/config.yml




- name: Configure WordPress
  shell: /usr/local/bin/wp core config
           --path="{{ wordpress_dir }}"
            --dbhost="{{ wordpress_database_address }}"
           --dbname="{{ wordpress_database }}"
           --dbuser="{{ wordpress_user }}"
           --dbpass="{{ wordpress_password }}"
  when: wordpress_is_downloaded.stat.exists == False

- name: Is WordPress installed?
  shell: /usr/local/bin/wp core is-installed
  args:
    chdir: "{{ wordpress_dir }}/"
  register: wordpress_is_installed
  ignore_errors: True  
  
- name: Install WordPress tables
  sudo: yes
  shell: /usr/local/bin/wp core install
            --path="{{ wordpress_dir }}"
            --url="{{ wordpress_home_url }}"
            --title="{{ wordpress_site_title }}"
            --admin_user="{{ wordpress_admin_user }}"
            --admin_password="{{ wordpress_admin_user_pass }}"
            --admin_email="{{ wordpress_admin_email }}"
  when: wordpress_is_installed|failed
  
- name: Apache config file for Wordpress
  copy:
    src=wordpress.conf
    dest=/etc/httpd/conf.d/wordpress.conf
    owner=root
    group=root
    mode=0644
    setype=httpd_config_t
  notify: restart httpd
  tags: wordpress
  
- name: Download Salts
  get_url:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    dest: "{{ wordpress_dir }}/wp-salts.php"
    seuser: system_u
    setype: httpd_sys_script_exec_t
    force: no
  notify: restart httpd
  
- name: Insert PHP start tag in Salts file
  lineinfile:
    dest: "{{ wordpress_dir }}/wp-salts.php"
    line: '<?php'
    state: present
    insertbefore: BOF
  notify: restart httpd

- name: Insert PHP end tag in Salts file
  lineinfile:
    dest: "{{ wordpress_dir }}/wp-salts.php"
    line: '?>'
    state: present
    insertafter: EOF
  notify: restart httpd
